server:
  servlet:
    context-path: /wonder-server
  port: 8088

spring:
  profiles:
    active: online
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  servlet:
    multipart:
      max-file-size: 10MB #单个文件的最大大小限制为10MB
      max-request-size: 20MB #整个请求体的最大大小限制为20MB，包括所有文件和其他表单字段

upload:
  path: E:/phpstudy_pro/WWW/upload
  allow-type: jpg,jpeg,gif,png,zip,7z,rar,txt,doc,docx,xls,xlsx,mp3,mp4

security:
  default-password: 123456
  ignore-path: /swagger/**,/webjars/**,/v2/**,/swagger-resources/**,/doc.html,/favicon.ico,/auth/**
  login-type:
    email: true
    username: true
    phone: true

  token:
    live-time: 24
    live-unit: HOURS
    refresh-time: 10
    refresh-unit: MINUTES

  request:
    enable-log: false

wx:
  miniapp:
    configs:
      - appid: wx487b66c8cba4bbd1
        secret: 249260b2d65387ff386c08d3a7021624

#      - appid: wxaa6742c27afc8584
#        secret: b8d8836a158c02cc9a6f155a51f4666f