server:
  servlet:
    context-path: /security-admin
  port: 8080

spring:
  profiles:
    active: local

wx:
  miniapp:
    configs:
      - appid: wx487b66c8cba4bbd1
        secret: 249260b2d65387ff386c08d3a7021624

#      - appid: wxaa6742c27afc8584
#        secret: b8d8836a158c02cc9a6f155a51f4666f