server:
  servlet:
    context-path: /security-admin
  port: 8080

spring:
  profiles:
    active: online

security:
  default-password: 123456
  ignore-path: /swagger/**,/webjars/**,/v2/**,/swagger-resources/**,/doc.html,/favicon.ico,/auth/**,/test/**
  login-type:
    email: true
    username: true
    phone: true

  cache:
    token:
      live-time: 24
      live-unit: HOURS
      refresh-time: 10
      refresh-unit: MINUTES

wx:
  miniapp:
    configs:
      - appid: wx487b66c8cba4bbd1
        secret: 249260b2d65387ff386c08d3a7021624

#      - appid: wxaa6742c27afc8584
#        secret: b8d8836a158c02cc9a6f155a51f4666f